mcreator_path=C:/Users/codeb/IdeaProjects/MCreator
mcreator_install=C:/Users/codeb/MCreator/MCreator20262

org.gradle.java.home=C:/Users/codeb/MCreator/MCreator20262/jdk
org.gradle.java.installations.paths=C:/Users/codeb/MCreator/MCreator20262/jdk
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=false
